//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Data.Exceptions
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataExceptionMessages
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataExceptionMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Platform.Data.Exceptions.DataExceptionMessages", typeof(DataExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The link [{0}] passed as an argument does not exist.".
        /// </summary>
        internal static string ArgumentLinkDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("ArgumentLinkDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The link [{0}] passed in argument [{1}] does not exist.".
        /// </summary>
        internal static string ArgumentLinkDoesNotExistWithParamName
        {
            get
            {
                return ResourceManager.GetString("ArgumentLinkDoesNotExistWithParamName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The link [{0}] passed as an argument has dependencies that prevent modification of its internal structure.".
        /// </summary>
        internal static string ArgumentLinkHasDependencies
        {
            get
            {
                return ResourceManager.GetString("ArgumentLinkHasDependencies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The link [{0}] passed in argument [{1}] has dependencies that prevent modification of its internal structure.".
        /// </summary>
        internal static string ArgumentLinkHasDependenciesWithParamName
        {
            get
            {
                return ResourceManager.GetString("ArgumentLinkHasDependenciesWithParamName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "A link with the same value already exists.".
        /// </summary>
        internal static string LinkWithSameValueAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("LinkWithSameValueAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The storage links limit has been reached.".
        /// </summary>
        internal static string LinksLimitReached
        {
            get
            {
                return ResourceManager.GetString("LinksLimitReached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The storage links limit has been reached ({0}).".
        /// </summary>
        internal static string LinksLimitReachedWithValue
        {
            get
            {
                return ResourceManager.GetString("LinksLimitReachedWithValue", resourceCulture);
            }
        }
    }
}
