<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>LinksPlatform's Platform.BlackBox Class Library - Activity recording and bug report generation</Description>
    <Copyright>Konstantin Diachenko</Copyright>
    <AssemblyTitle>Platform.BlackBox</AssemblyTitle>
    <VersionPrefix>0.0.1</VersionPrefix>
    <Authors>Konstantin Diachenko</Authors>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <AssemblyName>Platform.BlackBox</AssemblyName>
    <PackageId>Platform.BlackBox</PackageId>
    <PackageTags>LinksPlatform;BlackBox;Recording;BugReport;ActivityLog</PackageTags>
    <PackageIconUrl>https://raw.githubusercontent.com/Konard/LinksPlatform/master/doc/Avatar-rainbow.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/Konard/LinksPlatform</PackageProjectUrl>
    <PackageLicenseUrl>https://raw.githubusercontent.com/Konard/LinksPlatform/master/LICENSE</PackageLicenseUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>git://github.com/Konard/LinksPlatform</RepositoryUrl>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Platform.Data.Doublets" Version="0.6.10" />
    <PackageReference Include="Platform.Threading" Version="0.0.4" />
  </ItemGroup>

</Project>
