<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>LinksPlatform's Platform.CodeTransformations Class Library - Tool for managing breaking changes through code transformations</Description>
    <Copyright>Konstantin Diachenko</Copyright>
    <AssemblyTitle>Platform.CodeTransformations</AssemblyTitle>
    <VersionPrefix>0.0.1</VersionPrefix>
    <Authors>Konstantin Diachenko</Authors>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <AssemblyName>Platform.CodeTransformations</AssemblyName>
    <PackageId>Platform.CodeTransformations</PackageId>
    <PackageTags>LinksPlatform;CodeTransformations;Breaking Changes;Migration;Upgrade;Roslyn</PackageTags>
    <PackageIconUrl>https://raw.githubusercontent.com/Konard/LinksPlatform/master/doc/Avatar-rainbow.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/Konard/LinksPlatform/tree/master/Platform/Platform.CodeTransformations</PackageProjectUrl>
    <PackageLicenseUrl>https://raw.githubusercontent.com/Konard/LinksPlatform/master/LICENSE</PackageLicenseUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>git://github.com/Konard/LinksPlatform</RepositoryUrl>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
