<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>TDDStackOverflowDemo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Platform/Platform.Data.TDDStackOverflow/Platform.Data.TDDStackOverflow.csproj" />
  </ItemGroup>

</Project>
