using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Platform.CodeGeneration.Examples
{
    /// <summary>
    /// Roslyn source generator that automatically implements interfaces.
    /// Finds transformation paths from existing code to interface requirements.
    /// </summary>
    [Generator]
    public class AutoInterfaceImplementationGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // Register a syntax receiver that will be notified of syntax nodes
            context.RegisterForSyntaxNotifications(() => new AutoImplementSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is AutoImplementSyntaxReceiver receiver))
                return;

            // Process each interface marked with [AutoImplement] attribute
            foreach (var interfaceDeclaration in receiver.Interfaces)
            {
                var semanticModel = context.Compilation.GetSemanticModel(interfaceDeclaration.SyntaxTree);
                var interfaceSymbol = semanticModel.GetDeclaredSymbol(interfaceDeclaration) as INamedTypeSymbol;

                if (interfaceSymbol == null)
                    continue;

                // Generate implementation class
                var implementation = GenerateImplementation(interfaceSymbol, context);
                var fileName = $"{interfaceSymbol.Name}AutoImplementation.g.cs";
                context.AddSource(fileName, SourceText.From(implementation, Encoding.UTF8));
            }
        }

        private string GenerateImplementation(INamedTypeSymbol interfaceSymbol, GeneratorExecutionContext context)
        {
            var namespaceName = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
                ? "Generated"
                : interfaceSymbol.ContainingNamespace.ToDisplayString();

            var className = interfaceSymbol.Name.TrimStart('I') + "AutoImplementation";
            var sb = new StringBuilder();

            // File header
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This code was generated by AutoInterfaceImplementationGenerator");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // Class declaration
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Auto-generated implementation of {interfaceSymbol.Name}.");
            sb.AppendLine($"    /// Uses transformation paths to adapt existing code.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public partial class {className} : {interfaceSymbol.Name}");
            sb.AppendLine("    {");

            // Generate constructor
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Initializes a new instance of {className}.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public {className}()");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate methods
            var methods = interfaceSymbol.GetMembers().OfType<IMethodSymbol>();
            foreach (var method in methods)
            {
                GenerateMethod(sb, method);
            }

            // Generate properties
            var properties = interfaceSymbol.GetMembers().OfType<IPropertySymbol>();
            foreach (var property in properties)
            {
                GenerateProperty(sb, property);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void GenerateMethod(StringBuilder sb, IMethodSymbol method)
        {
            var returnType = method.ReturnType.ToDisplayString();
            var parameters = string.Join(", ", method.Parameters.Select(p =>
                $"{p.Type.ToDisplayString()} {p.Name}"));

            // Documentation
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Auto-generated implementation of {method.Name}.");
            sb.AppendLine($"        /// Finds and applies transformation path from available code.");
            sb.AppendLine($"        /// </summary>");

            foreach (var param in method.Parameters)
            {
                sb.AppendLine($"        /// <param name=\"{param.Name}\"></param>");
            }

            if (!method.ReturnsVoid)
            {
                sb.AppendLine($"        /// <returns></returns>");
            }

            // Method signature
            sb.AppendLine($"        public {returnType} {method.Name}({parameters})");
            sb.AppendLine("        {");

            // Method body
            sb.AppendLine($"            // TODO: Find transformation path from existing code");
            sb.AppendLine($"            // 1. Search for compatible methods in codebase");
            sb.AppendLine($"            // 2. Calculate transformation path from arguments to return value");
            sb.AppendLine($"            // 3. Generate implementation using transformations");
            sb.AppendLine();

            if (method.ReturnsVoid)
            {
                sb.AppendLine("            // No-op implementation");
            }
            else if (IsTaskType(method.ReturnType))
            {
                var taskType = ((INamedTypeSymbol)method.ReturnType).TypeArguments.FirstOrDefault();
                if (taskType != null)
                {
                    var defaultValue = GetDefaultValue(taskType);
                    sb.AppendLine($"            return Task.FromResult({defaultValue});");
                }
                else
                {
                    sb.AppendLine($"            return Task.CompletedTask;");
                }
            }
            else
            {
                var defaultValue = GetDefaultValue(method.ReturnType);
                sb.AppendLine($"            return {defaultValue};");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private void GenerateProperty(StringBuilder sb, IPropertySymbol property)
        {
            var propertyType = property.Type.ToDisplayString();

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Auto-generated property {property.Name}.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public {propertyType} {property.Name}");
            sb.AppendLine("        {");

            if (property.GetMethod != null)
            {
                sb.AppendLine("            get");
                sb.AppendLine("            {");
                var defaultValue = GetDefaultValue(property.Type);
                sb.AppendLine($"                return {defaultValue};");
                sb.AppendLine("            }");
            }

            if (property.SetMethod != null)
            {
                sb.AppendLine("            set");
                sb.AppendLine("            {");
                sb.AppendLine("                // TODO: Implement setter");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private bool IsTaskType(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol namedType)
            {
                var name = namedType.ConstructedFrom.ToDisplayString();
                return name == "System.Threading.Tasks.Task" ||
                       name == "System.Threading.Tasks.Task<TResult>";
            }
            return false;
        }

        private string GetDefaultValue(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return "false";
                case SpecialType.System_Byte:
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                    return "0";
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                    return "0.0";
                case SpecialType.System_Decimal:
                    return "0m";
                case SpecialType.System_String:
                    return "string.Empty";
                case SpecialType.System_Char:
                    return "'\\0'";
                default:
                    if (type.IsValueType)
                        return $"default({type.ToDisplayString()})";
                    return "null";
            }
        }
    }

    /// <summary>
    /// Syntax receiver that finds interfaces marked with [AutoImplement] attribute.
    /// </summary>
    internal class AutoImplementSyntaxReceiver : ISyntaxReceiver
    {
        public List<InterfaceDeclarationSyntax> Interfaces { get; } = new List<InterfaceDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // Look for interface declarations
            if (syntaxNode is InterfaceDeclarationSyntax interfaceDeclaration)
            {
                // Check if interface has [AutoImplement] attribute
                var hasAutoImplementAttribute = interfaceDeclaration.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .Any(a => a.Name.ToString().Contains("AutoImplement"));

                if (hasAutoImplementAttribute)
                {
                    Interfaces.Add(interfaceDeclaration);
                }
            }
        }
    }

    /// <summary>
    /// Attribute to mark interfaces for automatic implementation.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Interface)]
    public class AutoImplementAttribute : System.Attribute
    {
        /// <summary>
        /// Optional: Specify the source class to adapt from.
        /// </summary>
        public System.Type SourceType { get; set; }

        /// <summary>
        /// Optional: Allow lossy transformations (e.g., async to sync).
        /// </summary>
        public bool AllowLossyTransformations { get; set; } = false;
    }
}
