<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>LinksPlatform's Platform.Data.MongoDB Tests</Description>
    <Copyright>Konstantin Diachenko</Copyright>
    <AssemblyTitle>Platform.Data.MongoDB.Tests</AssemblyTitle>
    <VersionPrefix>0.0.1</VersionPrefix>
    <Authors>Konstantin Diachenko</Authors>
    <TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
    <AssemblyName>Platform.Data.MongoDB.Tests</AssemblyName>
    <PackageId>Platform.Data.MongoDB.Tests</PackageId>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
    <PackageReference Include="Platform.Data.Doublets" Version="0.6.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platform.Data.MongoDB\Platform.Data.MongoDB.csproj" />
  </ItemGroup>

</Project>
