<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>LinksPlatform's Platform.Data.Core Class Library</Description>
    <Copyright>Konstantin Diachenko</Copyright>
    <AssemblyTitle>Platform.Data.Core</AssemblyTitle>
    <VersionPrefix>0.0.1</VersionPrefix>
    <Authors>Konstantin Diachenko</Authors>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <AssemblyName>Platform.Data.Core</AssemblyName>
    <PackageId>Platform.Data.Core</PackageId>
    <PackageTags>LinksPlatform;Data;Core;Pairs;Doublets;MemoryManager</PackageTags>
    <PackageIconUrl>https://raw.githubusercontent.com/Konard/LinksPlatform/master/doc/Avatar-rainbow.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/Konard/LinksPlatform</PackageProjectUrl>
    <PackageLicenseUrl>https://raw.githubusercontent.com/Konard/LinksPlatform/master/LICENSE</PackageLicenseUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>git://github.com/Konard/LinksPlatform</RepositoryUrl>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

</Project>
