CC=i586-mingw32msvc-gcc
OPTS=-O3 --std=c99
#OPTS=-O3
DEFS=-DLINKS_DLL
libLinks.dll	: Link.h Link.c
	${CC} ${OPTS} ${DEFS} -c -o Timestamp.o Timestamp.c
	${CC} ${OPTS} ${DEFS} -c -o Link.o Link.c
	${CC} ${OPTS} ${DEFS} -c -o PersistentMemoryManager.o PersistentMemoryManager.c
	${CC} -shared -o libLinks.dll Link.o Timestamp.o PersistentMemoryManager.o -Wl,--out-implib,libLinks.a
