name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd Platform
        dotnet build
        cd ..
    - name: Run Tests
      run: |
        cd Platform
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults
        cd ..
    - name: Generate Coverage Report
      if: github.event_name == 'push'
      run: |
        cd Platform
        dotnet tool install -g dotnet-reportgenerator-globaltool || true
        reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./CoverageReport -reporttypes:Html || true
        cd ..
    - name: Publish Docs
      if: github.event_name == 'push'
      run: bash ./publish-docs.sh
