name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v2
    - name: Build for ${{ matrix.platform }}
      run: |
        cd Platform
        dotnet build -p:Platform=${{ matrix.platform }}
        cd ..
    - name: Publish Docs
      if: github.event_name == 'push'
      run: bash ./publish-docs.sh
